In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
file_path = "C:/Users/User/DASI/Week 3/Data_Mahasiswa.csv"
df = pd.read_csv(file_path, delimiter=";")

# Menampilkan beberapa baris pertama dataset
df.head()

,Email Address,Nama Lengkap Mahasiswa,NIM,Program Studi Mahasiswa,Angkatan Mahasiswa,Berapa lama waktu yang Anda habiskan menggunakan laptop setiap hari?,Apakah Anda biasanya menggunakan media sosial melalui laptop?,Berapa lama waktu yang Anda habiskan menggunakan media sosial melalui Laptop setiap hari?,Media sosial apa yang Anda aktifkan saat menggunakan laptop? (Centang semua yang sesuai),Jenis konten apa yang paling sering Anda tonton atau akses di media sosial Instagram melalui laptop? (Hubungkan dengan media sosial yang dipilih),...,Apakah Anda pernah mengikuti olimpiade atau kompetisi akademik?,Tingkat manakah Anda mengikuti olimpiade?,Berapa jumlah saudara yang Anda miliki?,Apa Pekerjaan Ayah Anda?,Apa Pendidikan Terakhir Ayah Anda?,Berapa Range Penghasilan Ayah Anda?,Apa Pekerjaan Ibu Anda?,Apa Pendidikan Terakhir Ibu Anda?,Berapa Rentang Penghasilan Ibu Anda?,Programming Skill
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43
1,NaN,Samuel Saut Royzeki Aritonang,11422026,Sarjana Terapan Teknologi Rekayasa Perangkat L...,2022,9 - 11 jam,Ya,3 - 5 jam,"Instagram, Tiktok","Hiburan (Video lucu, meme, dll.), Edukasi (Tut...",...,Tidak,NaN,05-Jun,telah meninggal dunia,SMP/sederajat,"Rp. 500,000 - Rp. 999,999",Pegawai negeri sipil,Diploma III,"Rp. 2,000,000 - Rp. 4,999,999",70
2,NaN,Calvin Josep Silaen,11422038,Sarjana Terapan Teknologi Rekayasa Perangkat L...,2022,6 - 8 jam,Tidak,NaN,NaN,NaN,...,Tidak,NaN,03-Apr,Petani/pekebun,Diploma IV atau Strata I,"Rp. 2,000,000 - Rp. 4,999,999",Perdagangan,Diploma IV atau Strata I,"Rp. 2,000,000 - Rp. 4,999,999",42
3,NaN,Indah Silitonga,11422060,Sarjana Terapan Teknologi Rekayasa Perangkat L...,2022,6 - 8 jam,Ya,0 - 2 jam,Instagram,"Hiburan (Video lucu, meme, dll.)",...,Tidak,NaN,03-Apr,Petani/pekebun,SMA/sederajat,"Rp. 1,000,000 - Rp. 1,999,999",Pegawai negeri sipil,Diploma IV atau Strata I,"Rp. 2,000,000 - Rp. 4,999,999",36
4,NaN,Asri Yohana Sirait,11422029,Sarjana Terapan Teknologi Rekayasa Perangkat L...,2022,3 - 5 jam,Tidak,NaN,NaN,NaN,...,Ya,"Tingkat Lokal (Kabupaten/Kota), Tingkat Region...",03-Apr,Petani/pekebun,SMA/sederajat,"Rp. 2,000,000 - Rp. 4,999,999",Petani/pekebun,SMA/sederajat,"Rp. 2,000,000 - Rp. 4,999,999",56

In [9]:
# Memilih fitur numerik yang akan dinormalisasi
numeric_features = ["Programming Skill"]

# Min-Max Scaling (0-1)
min_max_scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[numeric_features] = min_max_scaler.fit_transform(df[numeric_features])

# Standardization (Z-Score Normalization)
standard_scaler = StandardScaler()
df_standardized = df.copy()
df_standardized[numeric_features] = standard_scaler.fit_transform(df[numeric_features])

# Menampilkan hasil normalisasi pertama untuk dibandingkan
df_comparison = df[numeric_features].head(5).copy()
df_comparison["Programming Skill (MinMax)"] = df_minmax["Programming Skill"].head(5)
df_comparison["Programming Skill (Z-Score)"] = df_standardized["Programming Skill"].head(5)

df_comparison

   Programming Skill  Programming Skill (MinMax)  Programming Skill (Z-Score)
0                 43                    0.200000                    -1.076590
1                 70                    0.800000                     0.992694
2                 42                    0.177778                    -1.153230
3                 36                    0.044444                    -1.613070
4                 56                    0.488889                    -0.080268